### ISSUE TITLE
Setting Up documentation gives impossible instructions for trust policy

### ISSUE THREAD

**Issue by trehman-sb** [awsdocs/aws-glue-user-guide#2]
On the page https://docs.aws.amazon.com/glue/latest/ug/setting-up.html, the instructions state that the user should modify the role that is used for their ETL jobs to have the following as the Trust Policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["iam:PassRole"],
      "Effect": "Allow",
      "Resource": "arn:aws:iam::*:role/AWSGlueServiceRole*",
      "Condition": {
        "StringLike": {
          "iam:PassedToService": ["glue.amazonaws.com"]
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": ["glue.amazonaws.com"]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

This is not a valid Trust Policy, and attempting to edit a Trust Policy and putting this into it results in an error:

![image](https://user-images.githubusercontent.com/64552503/157716312-c6e875db-7ffb-4730-8bf3-a699aa7f81e8.png)

I _think_ that it's probably the case that people should add the first statement as a regular policy on their role, while keeping the second statement as the Trust Policy. However, this is not clear and the instructions are impossible to complete as written.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
